[build]
  command = "npm run build"
  publish = "dist"
[functions]
  directory = "functions"
  node_bundler = "esbuild"
[[plugins]]
package = "@netlify/plugin-functions-install-core"  

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"  
[[dev]]
  framework = "vue"